### ISSUE TITLE
Don't hardcode parser rules

### ISSUE THREAD

**Issue by lambdabaa** [lambdabaa/dav#11]
From @evert:

In parsing multi-status responses, I noticed you hardcoded a list of
webdav properties and built-in ways to decode them. I think the
multi-status parser should also simply just return a key->value map
with clark-notation xml elements for keys.

If the value is a simple string, keep it as is.. if it's not, we can
either choose to return the DOMElement, or we should provide a way to
do mappings between the xml element and some javascript object.

**Comment by halilibrahim** [comment]
This is an old issue but I've faced need of customized parser for my project. For now, I've solved my problem by using json strings as a workaround and writing this just to show a sample situation.

I'm developing a dav server based on [Symfony](https://packagist.org/packages/symfony/symfony) backend with [sabre/dav](https://packagist.org/packages/sabre/dav). The backend is going to be used on multiple applications with adding new database entities (customized per project).

Users can manage files with a third party webdav client. And also they can manage some extra data of files with customized client application which uses [lambdabaa/dav](https://github.com/lambdabaa/dav) as client.
Frontend client app has a file manager with a dynamic form consisting additional fields of file (such as fileIsValidUntil, fileVersion, etc...).

Frontend app doesn't know the fields. It fetches them from server, and renders the form of extra fields when user selects a file/folder.

Here's the client request:
```ts
const _listFolderRequest = dav.request.propfind({
    props: [
        {name: 'resourcetype', namespace: 'DAV:'},
        {name: 'permissions', namespace: 'DAV:'},
        {name: 'properties', namespace: 'DAV:'}
    ],
    depth: 1
});
```

Below method responses propFind properties request for a path.
```php
function getProperties() {
    $meta = $this->server->entityManager->getClassMetadata($this->entity->entity);
    $result = [];
    foreach ($meta->fieldMappings as $name => $field) {
        $reflectionProperty = $meta->reflFields[$name];
        
        // Fetching customized fields from entities
        if (!isset($field['inherited'])) {
            $titleAnnotation = $this->server->annotationReader->getPropertyAnnotation($reflectionProperty, Titles::class);
            if ($titleAnnotation) {
                $result[] = [
                    'key' => $name,
                    'value' => $this->data[$name],
                    'type' => $field['type'],
                    'length' => $field['length'],
                    'titles' => [
                        'tr' => $titleAnnotation->tr,
                        'en' => $titleAnnotation->en
                    ]
                ];
            }
        }
    }
    
-    // dav client can't parse xml if server returns the array
-    // return $result;

+    // If server returns json string, that value can be decoded and used at client app
+    return json_encode($result, JSON_HEX_APOS|JSON_HEX_QUOT);
}
```

And I also wanted to transfer the current user's permissions to client. If user doesn't have permission to delete but, tries to delete a folder with third party webdav client, server responses an exception. I wanted my frontend application to get permissions while listing folder, and hide delete button if user doesn't have delete permission.

Below method responses propFind permissions request for a path.
```php
public function getPermissions() {
    $permissions = $this->getCurrentUserPermissionsForNode();
    $result = json_encode([
        'add-folder' => $permissions->addFolder,
        'edit-folder' => $permissions->editFolder,
        'delete-folder' => $permissions->deleteFolder,
        'add-file' => $permissions->addFile,
        'edit-file' => $permissions->editFile,
        'delete-file' => $permissions->deleteFile
    ]);
-    // dav client can't parse xml if server returns the array
-    // return $result;
+    return json_encode($result);
}
```

It would be nice if we can tell dav client to fetch custom props such as permissions and properties.
