### ISSUE TITLE
How to get calendar events?

### ISSUE THREAD

**Issue by andreafalzetti** [lambdabaa/dav#113]
Hi, I have imported this library in my project and I managed to connect and retrieve the calendar informations.

I can't find a way to retrieve the events for a specific day. Could you please point me to the right way?

Thanks!

**Comment by himselfv** [comment]
JIC someone else looks for the same question, 

1. You have to pass ``loadObjects = true`` to ``createAccount`` for every calendar in the collection to have their ``objects`` collection populated.

2. Or call dav.loadCalendarObjects(calendar, { xhr: your.dav.Transport }) to get a Promise for the same objects[] array.

3. The array will contain event contents which you then need to parse manually. This lib doesn't seem to cover that.
