### ISSUE TITLE
400 bad request against Google API

### ISSUE THREAD

**Issue by pan100** [lambdabaa/dav#120]
Hi,

I am trying to connect to Google Calendar with Oauth2 in a React browser app. But I think I am doing it wrong. It returns 400 bad request.

My code (with obfuscated secrets)

```
var dav = require('dav');
var xhr = new dav.transport.OAuth2(
  new dav.Credentials({
    clientId:"something-secret.apps.googleusercontent.com",
    clientSecret:"something-secret",
    tokenUrl:"https://accounts.google.com/o/oauth2/token",
    username: 'something-secret',
    password: 'something-secret'
  })
);

dav.createAccount({ server: 'https://accounts.google.com/o/oauth2/auth', xhr: xhr })
.then(function(account) {
  // account instanceof dav.Account
  account.calendars.forEach(function(calendar) {
    console.log('Found calendar named ' + calendar.displayName);
    // etc.
  });
});
```

**Comment by pan100** [comment]
With debugging on (still hiding secrets:

[dav:accounts] Attempt service discovery.
dav.js:1894[dav:xmlhttprequest] Sending request data: code=&redirect_uri=&client_id=secret.apps.googleusercontent.com&client_secret=secret&grant_type=authorization_code

Does it need a redirect uri? and is grant_type wrong?

**Comment by pan100** [comment]
I did not know how to check the response but a friend helped me:

{
  "error" : "invalid_request",
  "error_description" : "Missing required parameter: code"
}

**Comment by jensModvig** [comment]
Any chance you have a working example, that is able to fetch some calendar events from the google calendar?
